@startuml
left to right direction
skinparam packageStyle rectangle

actor Admin
actor Student

rectangle "Assignment, Submission, Grade" {
  package "Admin Functions" {
    usecase "Quản lý bài tập" as ASG01
    usecase "Xem bài nộp theo assignment" as ASG02
    usecase "Xem chi tiết bài nộp" as ASG03
    usecase "Chấm điểm và feedback" as ASG04
  }

  package "Student Functions" {
    usecase "Xem bài tập được giao" as ASG05
    usecase "Xem chi tiết bài tập" as ASG06
    usecase "Nộp bài" as ASG07
    usecase "Cập nhật bài nộp" as ASG08
    usecase "Xem điểm và feedback" as ASG09
  }
}

Admin -- ASG01
Admin -- ASG02
Admin -- ASG03
Admin -- ASG04
Student -- ASG05
Student -- ASG06
Student -- ASG07
Student -- ASG08
Student -- ASG09
@enduml
